using UnityEngine;
using UnityEditor;

[CustomPropertyDrawer(typeof(SceneNameAttribute))]
public class SceneNameDrawer: PropertyDrawer 
{
    int sceneIndex = -1;
    GUIContent[] sceneNames;
    public override void OnGUI(Rect position, SerializedProperty property, GUIContent label) {
        if(EditorBuildSettings.scenes.Length == 0)
            return;
        
        if (sceneIndex == -1)
            GetSceneNameArray(property);

        int oldIndex = sceneIndex;
        sceneIndex = EditorGUI.Popup(position, label, sceneIndex, sceneNames);

        if (oldIndex != sceneIndex)
            property.stringValue = sceneNames[sceneIndex].text;
    }

    readonly string[] scenePathSplit = { "/", ".unity" };   //Delete the splash and .unity

    private void GetSceneNameArray(SerializedProperty property)
    {
        var scenes = EditorBuildSettings.scenes;
        //Init array
        sceneNames = new GUIContent[scenes.Length];

        for(int i = 0; i < sceneNames.Length; i++)
        {
            string path = scenes[i].path;
            string[] splitPath = path.Split(scenePathSplit, System.StringSplitOptions.RemoveEmptyEntries);
            string sceneName;
            if (splitPath.Length > 0)
            {
                sceneName = splitPath[splitPath.Length - 1];
            }
            else
            {
                sceneName = "Deleted Scene";
            }
            sceneNames[i] = new GUIContent(sceneName);
        }

        if (sceneNames.Length == 0)
        {
            sceneNames = new[] { new GUIContent("Not Scene Found. Check your build settings.") };
        }

        //Teleport name generated by script is empty
        if (!string.IsNullOrEmpty(property.stringValue))
        {
            bool isSceneNameFound = false;
            for (int i = 0; i < sceneNames.Length; i++)
            {
                if (sceneNames[i].text == property.stringValue)
                {
                    isSceneNameFound = true;
                    sceneIndex = i;
                    break;
                }
            }
            if (!isSceneNameFound)
                sceneIndex = 0;
        }
        else
        {
            sceneIndex = 0;
        }

        property.stringValue = sceneNames[sceneIndex].text;
    }
}